version: 2.1

jobs:
  test:
    docker:
      - image: cimg/go:1.18.0
    steps:
      - checkout
      - run:
          name: "Test"
          command: "go test"
workflows:
  test-workflow:
    jobs:
      - test
